### PR TITLE
Update Nginx to 1.25.1 and Alpine to 3.18

### PR DESCRIPTION
**Pull request by khiemdoan**
### Proposed changes

Describe the use case and detail of the change. If this PR addresses an issue on GitHub, make sure to include a link to that issue using one of the [supported keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) here in this description (not in the title of the PR).

### Checklist

Before creating a PR, run through this checklist and mark each as complete.

- [x] I have read the [`CONTRIBUTING`](https://github.com/nginxinc/docker-nginx-unprivileged/blob/main/CONTRIBUTING.md) document.
- [x] I have tested that the NGINX Unprivileged Docker images build correctly on all supported platforms (check out the [`README`](https://github.com/nginxinc/docker-nginx-unprivileged/blob/main/README.md) for more details).
- [ ] I have deployed the NGINX Unprivileged Docker images on an unprivileged environment and checked that they run correctly.
- [ ] I have updated any relevant documentation ([`README`](https://github.com/nginxinc/docker-nginx-unprivileged/blob/main/README.md))

### CODE REVIEW

**Comment by alessfg** [comment]
Per https://github.com/nginxinc/docker-nginx/pull/776#issuecomment-1541297127 -- Alpine 3.18 images are not yet available

**Comment by DataMinded** [comment]
Any movement on this ?

**Comment by alessfg** [comment]
Not for now. I'd suggest keeping an eye out on https://nginx.org/en/linux_packages.html. Once Alpine 3.18 images are available, the list there will be updated (and the Docker images will likely follow in the coming days after the release) 😄

**Comment by alessfg** [comment]
Finally added Alpine 3.18 in https://github.com/nginxinc/docker-nginx-unprivileged/commit/3a95eb590e852dda70d392883039a95ac9fbbf65

**Pull request closed without merging**
