### PR TITLE
Add IPv6 support for local-resolvers substitution script

### PR DESCRIPTION
**Pull request by alessfg**
### Proposed changes

This PR ports the latest updates made to the upstream https://github.com/nginxinc/docker-nginx image. It adds IPv6 support for local-resolvers substitution script, addresses an Alpine bug, and fixes some shell linter warnings.

### Checklist

Before creating a PR, run through this checklist and mark each as complete:

- [x] I have read the [`CONTRIBUTING`](https://github.com/nginxinc/docker-nginx-unprivileged/blob/main/CONTRIBUTING.md) document
- [x] I have run `./update.sh` and ensured all entrypoint/Dockerfile template changes have been applied to the relevant image entrypoint scripts & Dockerfiles
- [x] I have tested that the NGINX Unprivileged Docker images build and run correctly on all supported architectures on an unprivileged environment (check out the [`README`](https://github.com/nginxinc/docker-nginx-unprivileged/blob/main/README.md) for more details)
- [x] I have updated any relevant documentation ([`README`](https://github.com/nginxinc/docker-nginx-unprivileged/blob/main/README.md))

### CODE REVIEW

**Comment by wanisfahmyDE** [comment]
hey @alessfg, is this PR fixed with the 1.25.4 release?
referring to this issue https://github.com/nginxinc/docker-nginx-unprivileged/issues/114

**Comment by alessfg** [comment]
Not quite. That issue is caused by replacing the `default.conf` file with a different one before the script runs. This PR fixes an issue that led to IPv6 addresses not being correctly templated even when using the "default" `default.conf`.

**Comment by alessfg** [comment]
The issue you are describing should have been fixed by this PR (you seem to be missing the IPv6 square brackets, which this PR addresses).

**Comment by wanisfahmyDE** [comment]
Thanks for the hint, this is really helpful. Since devlake uses a custom script for startup https://github.com/apache/incubator-devlake/blob/main/config-ui/nginx.sh#L27, I will submit a PR there to match the changes from this PR.

**Pull request merged**
